---
ID: "32a26ec0-e8b0-4fc1-b9c5-5f329535aac1"
Parent: "59b41b5f-e22e-460b-941e-fb64fe8da8fc"
Template: "a6868d65-d612-401f-a40a-cd5ba0857b81"
Path: /sitecore/system/Settings/Services/API Keys/default
SharedFields:
- ID: "1e7a5aa7-a27d-46fa-bd93-1bfe3c04efe2"
  Hint: Impersonation User
  Value: |
    extranet\anonymous
- ID: "780c8e48-fe03-4a73-90dc-9bb5296b95d7"
  Hint: CORS Origins
  Value: *
- ID: "99ba91ec-f0d3-4372-b638-67c2402a2484"
  Hint: AllowedControllers
  Value: *
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f7fd5192-c314-4dd0-9ad4-7420b692824f"
