name: Publish nextjs image 
on:
  workflow_dispatch: {}
  push:
    branches:
      - 'main'
    paths:
      - 'nextjs/**'

jobs:
  publish-nextjs-image:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}     
 

      - name: Build CM Docker image
        run: |
          docker build ./nextjs `
            --tag sitecore-nextjs:18.14.2 `
            --build-arg PARENT_IMAGE=mcr.microsoft.com/windows/nanoserver:1809 `
            --build-arg NODEJS_VERSION=18.14.2 `            
          
          docker tag sitecore-nextjs:18.14.2 ghcr.io/ampach/sitecore-nextjs:18.14.2
          docker push ghcr.io/ampach/sitecore-nextjs:18.14.2
