name: Publish MSSQL-INIT image 
on:
  workflow_dispatch: {}
  push:
    branches:
      - 'main'
    paths:
      - 'mssql-init/**'

jobs:
  publish-nextjs-image:
    permissions: write-all
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}     
 

      - name: Build MSSQL-INIT Docker image
        run: |
          docker build ./mssql-init `
            --tag sitecore-sxa-spe-jss:10.3-ltsc2022 `
            --build-arg HEADLESS_SERVICES_IMAGE=scr.sitecore.com/sxp/modules/sitecore-sxa-xm1-assets:10.3-ltsc2022 `
            --build-arg SPE_IMAGE=scr.sitecore.com/sxp/modules/sitecore-spe-assets:6.4.0.65-ltsc2022 `
            --build-arg PARENT_IMAGE=scr.sitecore.com/sxp/sitecore-xm1-mssql-init:10.3-ltsc2022
          
          docker tag sitecore-nextjs:10.3-ltsc2022 ghcr.io/ampach/sitecore-nextjs:10.3-ltsc2022
          docker push ghcr.io/ampach/sitecore-nextjs:10.3-ltsc2022
