name: Publish Identity Server image 
on:
  workflow_dispatch: {}
  push:
    branches:
      - 'main'
    paths:
      - 'id/**'

jobs:
  publish-id-image:
    permissions: write-all
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}     

      - name: Replace tokens
        shell: pwsh
        run: |
          (Get-Content ./id/Config/Sitecore.IdentityServer.ClientID.xml) -replace '{client-name}', '${{ secrets.SITECORE_IDENTITY_CLIENT_NAME }}' -replace '{client-secret}', '${{ secrets.SITECORE_IDENTITY_CLIENT_SECRET }}' | Set-Content -Path ./id/Config/Sitecore.IdentityServer.ClientID.xml -Force
      
      - name: Build ID Docker image
        run: |
          docker build ./id `
            --tag sitecore-id:10.3-ltsc2022 `
            --build-arg PARENT_IMAGE=scr.sitecore.com/sxp/sitecore-id7:10.3-ltsc2022             
          
          docker tag sitecore-id:10.3-ltsc2022 ghcr.io/ampach/sitecore-id:10.3-ltsc2022
          docker push ghcr.io/ampach/sitecore-id:10.3-ltsc2022
